trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release

steps:
  - task: UseDotNet@2
    displayName: Install .NET SDK
    inputs:
      packageType: sdk
      version: 9.0.300

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '**/*.sln'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/*.sln'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/*.sln'
      arguments: '--configuration $(buildConfiguration) --logger trx --results-directory $(Build.ArtifactStagingDirectory)/test-results'
      publishTestResults: true
      testRunTitle: Unit Tests

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      projects: 'src/NameSorter.App/NameSorter.App.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'

  - task: PublishBuildArtifacts@1
    displayName: Publish build artifact
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/publish
      ArtifactName: drop
      publishLocation: Container
